# shellcheck disable=SC1090

bindkey -e

fpath=( ~/.zsh/completion "${fpath[@]}" )

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions/:$FPATH
fi

autoload -Uz compinit; compinit

export PATH="${HOMEBREW_PREFIX}/opt/openssl/bin:$PATH"

if [ -d "$HOME/.env.d" ]; then
  for i in "$HOME/.env.d/"*.sh; do
    if [ -r "$i" ]; then
      . "$i"
      export ZSH_SCRIPTS=${ZSH_SCRIPTS}:${i##*/}
    fi
  done
  unset i
fi
