#!/bin/sh
#
# ~/.xinitrc
#
# basic X startup

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load style
[ -f "${HOME}/.Xresources" ] && xrdb -merge ${HOME}/.Xresources

# set wallpaper
WALLPAPER_PATH=${HOME}/pictures/wallpapers/Ju5PuBC-arch-linux-wallpaper.jpg
if [ -f $WALLPAPER_PATH ]; then
    feh --bg-fill $WALLPAPER_PATH &
fi

# enable screensaver
/bin/xss-lock -- /bin/i3lock -c 263238 -n &

# start wm
exec i3
