# Taps
tap "homebrew/services"
tap "homebrew/homebrew-bol"

# bol apps
brew "homebrew/homebrew-bol/proxer"
brew "homebrew/homebrew-bol/bol-cli"

# System
brew "bash"
brew "bat"
brew "bottom"
brew "coreutils"
brew "curl"
brew "eza"
brew "fd"
brew "fzf"
brew "gopass"
brew "gnupg"
brew "htop"
brew "mas"
brew "ncurses"
brew "nushell"
brew "p7zip"
brew "pandoc"
brew "pinentry-mac"
brew "plantuml"
brew "rcm"
brew "rename"
brew "ripgrep"
brew "sponge"
brew "starship"
brew "watch"
brew "wget"
brew "zellij"
brew "zoxide"
brew "zsh-syntax-highlighting"
cask "alacritty"
cask "syncthing"

# Ops
brew "k9s"
brew "kubectx", args: ["ignore-dependencies"]
brew "stern"

# Helix and addons
brew "helix"
brew "bash-language-server"
brew "typescript-language-server"
brew "marksman"
brew "vscode-langservers-extracted"
brew "yaml-language-server"
brew "taplo"

# Versioning and packaging
brew "git"
brew "git-crypt"
brew "git-delta"
brew "gitui"

# Dev misc
cask "emacs"
brew "direnv"
brew "golang"
brew "shellcheck"
brew "jless"
brew "jq"
brew "postgresql@15"

# Java/Kotlin
brew "ktlint"
brew "maven"
brew "jenv"
cask "zulu@21"

# Javascript/Node
brew "fnm"

# Python
brew "poetry"
brew "pyenv"

# Docker / gcloud
cask "google-cloud-sdk"
brew "colima"
brew "qemu" # required for colima
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "k9s"
brew "kubectx", args: ["ignore-dependencies"]
brew "stern"

# DevOps tooling
brew "httpie"
brew "libpq"
brew "libyaml"
brew "neovim"
brew "yq"

# Generic tools
brew "bitwarden-cli"
cask "bitwarden"
cask "browserosaurus"
cask "font-fira-code-nerd-font"

cask "logseq"
cask "obsidian"

cask "element"
cask "signal"
