#!/usr/bin/env bash

# get path where script is running from:
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# backups are written to path in $1 or into script path if empty
backup_path=${1:-"$script_path"}

backup_dest="${backup_path}/$(uname -n)_$(date +%Y%m%d_%H%M)"
#backup_dest="${backup_path}/$(hostname -s)_$(date +%Y%m%d)"
backup_include="${script_path}/backup_include"
backup_exclude="${script_path}/backup_exclude"

echo "Creating backup into $backup_dest"
echo "Backup exclude:"
cat "$backup_exclude"
echo
echo "Backup include:"
cat "$backup_include"
echo

# tarbal
tar --exclude-from="$backup_exclude" \
  --files-from="$backup_include" \
  -cf "$backup_dest".tar

# encrypt the backup
gpg -c "$backup_dest".tar
