# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# System
#brew "bash"
#brew "md5sha1sum"
#brew "ncurses"
#brew "p7zip"
#brew "sponge"
#brew "watch"

# Python
brew "poetry"
brew "pipenv"
brew "pyenv"
brew "pyenv-virtualenv"

# Nodejs
brew "nvm"

# Casks 
cask "browserosaurus" 
cask "discord"
cask "gimp"
cask "obsidian"
cask "rectangle"
