format = "$hostname$directory$nix_shell$git_branch$git_commit$git_status$fill$golang$java$kotlin$nodejs$php$python$ruby$rust$kubernetes$line_break$status$character"

[directory]
format = "[$path[$read_only]($read_only_style)]($style) "
repo_root_format = "[$before_root_path]($style)[$repo_root]($repo_root_style)[$path[$read_only]($read_only_style)]($style) "
repo_root_style = "bold fg:220"
style = "bold blue"

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "

[git_commit]
format = "[$hash]($style) "

[git_status]
ahead = "[↑$count](blue)"
behind = "[↓$count](red)"
conflicted = "✗"
deleted = "[✗$count](red)"
diverged = "[↑$\\{ahead_count\\}](blue)[↓$\\{behind_count\\}](red)"
format = "([$all_status$ahead_behind]($style)) "
modified = "[+$count](red)"
staged = "[¤$count](green)"
stashed = "📦"
style = "green"
untracked = "[…](red)"
up_to_date = "✔"

[golang]
format = "[$symbol($version)]($style) "

[hostname]
format = "[$hostname]($style):"

[java]
format = "[$symbol($version)]($style) "

[kotlin]
format = "[$symbol($version)]($style) "

[kubernetes]
disabled = false
format = "[$context/$namespace]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[php]
format = "[$symbol($version)]($style) "

[python]
format = "[${symbol}${pyenv_prefix}(${version})(($virtualenv))]($style) "

[ruby]
format = "[$symbol($version)]($style) "

[rust]
format = "[$symbol($version)]($style) "

[status]
disabled = false
not_executable_symbol = ""
not_found_symbol = ""
