[icons]
name = "awesome"

[theme]
name = "slick"

# [theme.overrides]
# idle_bg = "#222222"
# idle_fg = "#cfcfcf"
# info_bg = "#222222"
# info_fg = "#ffffff"
# good_bg = "#222222"
# good_fg = "#ffffff"
# warning_bg = "#222222"
# # warning_fg = "#ffffff"
# critical_bg = "#ff2222"
# critical_fg = "#ffffff"

# separator = "|"
# separator_fg = "#666666"
# separator_bg = "#222222"

# [[block]]
# block = "custom"
# command = "echo -n  $(/home/qmeijer/go/bin/gerrit-cli -user qmeijer -pass $(gopass show websites/gerrit.tools.bol.com/qmeijer | head -1))"
# interval = 120

#[[block]]
#block = "pacman"
#interval = 10

[[block]]
block = "load"
interval = 1
format = "{5m}"

#[[block]]
#block = "temperature"

[[block]]
block = "memory"
format_mem = "{Mup}%"
warning_mem = 90.0
critical_mem = 95.0
interval = 5

[[block]]
block = "disk_space"
warning = 10
alert = 5

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "net"
device = "enp0s31f6"
speed_up = false
speed_down = false

#[[block]]
#block = "custom"
#command = "/home/qmeijer/bin/vpn-status"

#[[block]]
#block = "bluetooth"
#mac = "1C:52:16:19:39:48"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
