{
  "colors": {
    "bright": {
      "black": "0x4c4c4c",
      "blue": "0xb3deef",
      "cyan": "0x73cef4",
      "green": "0xc9d05c",
      "magenta": "0xd3b987",
      "red": "0xf43753",
      "white": "0xfeffff",
      "yellow": "0xffc24b"
    },
    "normal": {
      "black": "0x282828",
      "blue": "0xb3deef",
      "cyan": "0x73cef4",
      "green": "0xc9d05c",
      "magenta": "0xd3b987",
      "red": "0xf43753",
      "white": "0xeeeeee",
      "yellow": "0xffc24b"
    },
    "primary": {
      "background": "0x282828",
      "foreground": "0xeeeeee"
    }
  },
  "cursor": {
    "style": "beam"
  },
  "font": {
    "bold": {
      "family": "FiraCode Nerd Font",
      "style": "Bold"
    },
    "bold_italic": {
      "family": "FiraCode Nerd Font",
      "style": "Bold Italic"
    },
    "italic": {
      "family": "FiraCode Nerd Font",
      "style": "Italic"
    },
    "normal": {
      "family": "FiraCode Nerd Font",
      "style": "Regular"
    },
    "size": 14
  },
  "selection": {
    "save_to_clipboard": true
  },
  "shell": {
    "args": [
      "-fp",
      "qmeijer"
    ],
    "program": "login"
  },
  "window": {
    "option_as_alt": "Both"
  }
}
